### ISSUE TITLE
RCON fails to show power input.

### ISSUE THREAD

**Issue by Hawk-v3** [Occulus-Server/Occulus-Eris#137]
#### Description of issue

![image](https://user-images.githubusercontent.com/1232355/104127721-ae84cc00-535b-11eb-88a5-1bccfd26989f.png)

These SMESs are charging and receiving power. However, unless you go and see them in person, the RCON displays 0 input charge.

#### Difference between expected and actual behavior

It should show the amount of charge the SMES is receiving.

#### Steps to reproduce 

Start engine. Check Engine Room SMESs (Partially or fully charging). Check RCON (0kw Input)

#### Length of time in which bug has been known to occur

At least a week.

#### Client version, Server revision & Game ID

Server revision: master - 2021-01-10
a5dcecc59d76ab0225e5e0240cc046b881d47dd4

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by zackerycodestoo** [comment]
I'm investigating this, so here are some notes -- the RCON console appears to be drawing from an SMES variable called input_available. In the SMES file, input_available is zeroed and described as 'amount of charge available from input last tick'. I don't see anything modifying input_available _yet_. I'm still digging, but it seems like it's zeroed out because it was never defined in the first place...
