### ISSUE TITLE
Vote Window does not close when using the X button.

### ISSUE THREAD

**Issue by ShadzFen** [Occulus-Server/Occulus-Eris#2]
#### Description of issue
https://github.com/Eclipse-Station/NEV-Northern-Light/issues/73
That issue has the relevant info. The vote window will (semi-reliably) close if you spam the Close button and then press the X, but will continue to popup if you close it without spamming the Close button.

#### Difference between expected and actual behavior
It should just close and not pop back up whenever you click either Close or the X button.

#### Steps to reproduce 
Start a vote, try to close the window.

#### Specific information for locating

Check the Issue ticket on Eclipse's Github.

#### Length of time in which bug has been known to occur

Since the 14th of May.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by Michiyamenotehifunana** [comment]
This is due to a fundamental flaw in the voting system which iterates through all players who _should_ have the window open, and adds them to a list of players who have the voting window open. Every tick, the server forcibly opens the voting window for all the players in that list. Getting out of that list reliably is the hard part.

Furthermore, this crappy list approach causes a lot of issues with actually casting the vote, especially if you are experiencing some lag.

The only way to solve this is to port over Polaris' reworked voting system, but that's a proper pain in the ass as it has to be done upstream for best results.

**Comment by ShadzFen** [comment]
Yeah but as far as we're aware, upstream doesn't even have this issue at all. There are no reports of this bug on the Eris github (last I checked at least, which was about 2 weeks ago), and the only report is on the Eclipse github.

**Comment by Michiyamenotehifunana** [comment]
There's no more X button on the vote window, and the close button actually permanently closes the vote window now. I guess we can close this issue.

It should be noted, however, that some people are apparently still having issues even with the vote window set back to its default state.

**Comment by ShadzFen** [comment]
If that becomes a big issue we'll make another ticket about it. For now, closing this damned issue ticket once and for all. It only took 6 months...
