### ISSUE TITLE
Autodoc needs performance improvements

### ISSUE THREAD

**Issue by zackerycodestoo** [Occulus-Server/Occulus-Eris#259]
#### Description of issue

In a recent round, a player had broken ribs. They used the autodoc and tried to fix their bones, but the Autodoc went into a spam of 'treatment complete' instead of actually fixing anything. It still ate their money.

This information is secondhand from the player who suffered the broken ribs.

#### Steps to reproduce 

1. Have broken ribs.
2. Try to fix broken ribs in the autodoc.
3. Autodoc spams 'treatment complete'

#### Specific information for locating

The autodoc currently in medbay

#### Length of time in which bug has been known to occur

Since the autodoc machine was implemented

#### Client version, Server revision & Game ID

![image](https://user-images.githubusercontent.com/77511162/108062069-46469b80-7027-11eb-83b5-79b113d8f412.png)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by vulppine** [comment]
# Analysis

looked through, found out the reason why the "Treatment Complete" spam occurs:

[lines 112 - 115, autodoc.dm](https://github.com/Occulus-Server/Occulus-Eris/blob/cbed9665631e1a6a5a2bcbaaea2487e868ed0055/code/modules/surgery/autodoc.dm#L112)
```
/datum/autodoc/proc/process_note(var/datum/autodoc_patchnote/patchnote)
	if(!patchnote.surgery_operations)
		to_chat(patient, SPAN_NOTICE("Treatment complete."))
		return TRUE
```

what occurs is that `process_note()` checks if the current patchnote has a zero-value for its current processed note's `surgery_operations` - if it does, it outputs "Treatment complete" to the user in chat, and returns true, otherwise it continues execution

this occurs for every patchnote in `picked_patchnotes` - expected behavior, as `Process()` uses the return value to indicate whether or not the treatment was actually performed in order to advance the current treatment step, while also making the processing time a little longer (further details as to how the iteration occurs can be found in the [loop spawned in the `start()` proc](https://github.com/Occulus-Server/Occulus-Eris/blob/cbed9665631e1a6a5a2bcbaaea2487e868ed0055/code/modules/surgery/autodoc.dm#L301))

[proc `Process()` autodoc.dm](https://github.com/Occulus-Server/Occulus-Eris/blob/cbed9665631e1a6a5a2bcbaaea2487e868ed0055/code/modules/surgery/autodoc.dm#L186)
```
/datum/autodoc/Process()
...
	if(current_step > picked_patchnotes.len)
		stop()
		scan_user(patient)
...
		if(process_note(picked_patchnotes[current_step]))
			current_step++
```

the issue is that `picked_patchnotes` is populated with *every* single scannable thing with damage, no matter if it was picked from the UI or not:

[proc `scan_user()`, autodoc.dm](https://github.com/Occulus-Server/Occulus-Eris/blob/cbed9665631e1a6a5a2bcbaaea2487e868ed0055/code/modules/surgery/autodoc.dm#L54)
```
/datum/autodoc/proc/scan_user()
...
	if(toxnote.surgery_operations)
		scanned_patchnotes.Add(toxnote)
		picked_patchnotes.Add(toxnote.Copy())
...
	if(AUTODOC_DAMAGE in possible_operations)
		for(var/obj/item/organ/internal/internal in patient.internal_organs)
...
				scanned_patchnotes.Add(patchnote)
				picked_patchnotes.Add(patchnote.Copy())
...
	for(var/obj/item/organ/external/external in patient.bad_external_organs)
...
		if(patchnote.surgery_operations)
			scanned_patchnotes.Add(patchnote)
			picked_patchnotes.Add(patchnote.Copy())
...
```

![2021-02-16_scrot](https://user-images.githubusercontent.com/76629141/108151009-9efb5000-708a-11eb-902d-8310f8823dd1.png)

to confirm, what occurs in UI is that whatever thing is selected by the user to be operated on just has its relevant bit set in its `surgery_operations` var:

[proc `Topic()`, autodoc.dm](https://github.com/Occulus-Server/Occulus-Eris/blob/cbed9665631e1a6a5a2bcbaaea2487e868ed0055/code/modules/surgery/autodoc.dm#L307)

```
/datum/autodoc/Topic(href, href_list)
...
		if(picked_patchnotes[id].surgery_operations & op)
			picked_patchnotes[id].surgery_operations &= ~op
		else
			picked_patchnotes[id].surgery_operations |= op
```

this means that any scannable thing that *has damage* is automatically 'operated on', even if there were no operations picked, which is what causes the "Treatment complete" spam to occur - as all organ patchnotes without operations automatically have a zero-value for their `surgery_operations`

# Testing

now, bones *do* get fixed - however, it takes a very long time if the patient has a lot of damage on their body, as the autodoc iterates over every single organ with damage (since `picked_patchnotes` populates with every single damaged organ as shown above), and it equally causes the "Treatment complete" spam as shown above (due to the way that the autodoc checks if an organ has been treated or not) - it takes a long time because `Process()` waits a certain amount of time before continuing, which would be expected behavior were it not for it processing non-selected organs as well

so it's not an issue of bones getting fixed - but more rather, the performance of the autodoc

# Summary:
- the `picked_patchnotes` var is populated with every scanned organ
- `process_note()` checks if the current patchnote being iterated on has a non-zero `surgery_operations` - since all possible things to operate on are in `picked_patchnotes`, selected or not, it prints "Treatment complete" to the user if the current organ being iterated over has a zero-value `surgery_operations` due to it not having any operations selected, leading to it being printed without any context to the user
- `Process()` as a result takes a very long time, as it iterates over every single damaged thing in the player character's body, rather than the ones that the user selected

**Comment by zackerycodestoo** [comment]
Thank you for the very in-depth investigation. We'll see if we can clean this code up...
