### ISSUE TITLE
Syringe Injection code does not check armor coverage to prevent needles

### ISSUE THREAD

**Issue by Jamini** [Occulus-Server/Occulus-Eris#40]
#### Description of issue

Injection code should check part coverage for preventing injection

#### Difference between expected and actual behavior

Currently all armor blocks injection, even armor that doesn't cover limbs.

#### Steps to reproduce 

1. Put on armor
2. Pick up a needle
3. Fill needle
4. Attempt to inject self

#### Length of time in which bug has been known to occur

This has been the case as long as Occulus and Syzygy has existed. Eris likely did not port changes that were made to the bay branches when they split

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by ShadzFen** [comment]
Try to be a little more specific on what exactly the changes that have to be made are. Specifically in the differences between expected and actual behaviour. For example:

- Currently, body armour that covers the chest and lower body blocks injecting the chest, lower body, both arms and both hands.
- Body armour that covers the chest and lower body should block injecting the chest and lower body, **NOT** the arms and hands. 

Most developers won't even bother asking what exactly the changes that need to made are if they don't understand it entirely the first time reading the description, and then the bug never gets fixed.

**Comment by Leon9621** [comment]
Hey, I know this has been sitting here for a bit, but I wanted to take a look at an issue, see if I could find out why it was going bad, and this one seemed like (potentially) the easiest to identify why. I believe the issue is here-

https://github.com/Occulus-Server/Occulus-Eris/blob/fcb04e3d7d199a22c67f06bdc348a39c2b78ab5b/code/modules/mob/living/carbon/human/human.dm#L1359

Specifically, the check for whether or not the limb can be injected (Making sure it's there, seeing if it has item flags, and seeing if one of those flags is THICKMATERIAL) for the head. After that? It runs the same check, but far more generalized. If you're wearing a suit with THICKMATERIAL at all, then you simply can't be injected on any of the limbs, even if they're not protected by the armor.
